### PR TITLE
Fix SSH config %h using Host

### PR DESCRIPTION
**Pull request by emc2314**
This commit fix issue #4503

### CODE REVIEW

**Comment by wez** [comment]
Thanks for this; please add a test case, because it isn't obvious why part of this PR is removing some code, which is a great sign that there needs to be more test coverage!

**Comment by emc2314** [comment]
Sorry I didn't check the test case and I didn't realize that to fix issue #4503 actually requires two-phase parsing which is not supported yet. I tried to modify the ```token_map``` during single-phase parsing but I don't know whether it's appropriate. Thanks for reviewing.

**Comment by wheatdog** [comment]
I think we still need to update `token_map["%h"]` right after resolving hostname. How about this implementation?

```
diff --git a/wezterm-ssh/src/config.rs b/wezterm-ssh/src/config.rs
index 0ccba7572..81e4e95b8 100644
--- a/wezterm-ssh/src/config.rs
+++ b/wezterm-ssh/src/config.rs
@@ -532,7 +532,18 @@ impl Config {
         }
 
         let mut token_map = self.tokens.clone();
+
         token_map.insert("%h".to_string(), host.to_string());
+        result
+            .entry("hostname".to_string())
+            .and_modify(|curr| {
+                if let Some(tokens) = self.should_expand_tokens("hostname") {
+                    self.expand_tokens(curr, tokens, &token_map);
+                }
+            })
+            .or_insert_with(|| host.to_string());
+        token_map.insert("%h".to_string(), result["hostname"].to_string());
+
         token_map.insert("%n".to_string(), host.to_string());
         token_map.insert("%r".to_string(), target_user.to_string());
         token_map.insert(
@@ -553,10 +564,6 @@ impl Config {
             }
         }
 
-        result
-            .entry("hostname".to_string())
-            .or_insert_with(|| host.to_string());
-
         result
             .entry("port".to_string())
             .or_insert_with(|| "22".to_string());

```

**Comment by emc2314** [comment]
> I think we still need to update `token_map["%h"]` as early as we can. How about this implementation?
> 
> ```
> diff --git a/wezterm-ssh/src/config.rs b/wezterm-ssh/src/config.rs
> index 0ccba7572..81e4e95b8 100644
> --- a/wezterm-ssh/src/config.rs
> +++ b/wezterm-ssh/src/config.rs
> @@ -532,7 +532,18 @@ impl Config {
>          }
>  
>          let mut token_map = self.tokens.clone();
> +
>          token_map.insert("%h".to_string(), host.to_string());
> +        result
> +            .entry("hostname".to_string())
> +            .and_modify(|curr| {
> +                if let Some(tokens) = self.should_expand_tokens("hostname") {
> +                    self.expand_tokens(curr, tokens, &token_map);
> +                }
> +            })
> +            .or_insert_with(|| host.to_string());
> +        token_map.insert("%h".to_string(), result["hostname"].to_string());
> +
>          token_map.insert("%n".to_string(), host.to_string());
>          token_map.insert("%r".to_string(), target_user.to_string());
>          token_map.insert(
> @@ -553,10 +564,6 @@ impl Config {
>              }
>          }
>  
> -        result
> -            .entry("hostname".to_string())
> -            .or_insert_with(|| host.to_string());
> -
>          result
>              .entry("port".to_string())
>              .or_insert_with(|| "22".to_string());
> ```

Thanks for your guidance! I totally agree with you.

**Comment by wez** [comment]
Thanks!

**Pull request merged**
