### PR TITLE
Addingstdredirects

### PR DESCRIPTION
**Pull request by robinbernon**

### CODE REVIEW

**Comment by robinbernon** [comment]
@wez

**Comment by robinbernon** [comment]
This has the change

**Comment by robinbernon** [comment]
@wez it timed out. How come it takes so long? why are you installing rust each time on the container? Do you not want to cache the installation to avoid the long check times?

**Comment by wez** [comment]
I don't think this PR is rebased on https://github.com/wez/wezterm/commit/caed905626123cf5cec1368377330413a3e1ab1a to fix the rustup bug that causes the timeout on freebsd.

I think the code changes here look good now; if you can test the gag changes and confirm that it's working as intended, I'll merge this.

**Comment by robinbernon** [comment]
@wez have done a rebase now.

**Comment by robinbernon** [comment]
@wez freebsd passed

**Comment by robinbernon** [comment]
@wez would it be possible for you to publish another version of the crate so I can also update the gag crate with the changes?

**Comment by wez** [comment]
Yeah, I'll make a release: I've got an API change that I want to verify before I do that (removing anyhow and replacing with a local Error type)

**Comment by robinbernon** [comment]
> Yeah, I'll make a release: I've got an API change that I want to verify before I do that (removing anyhow and replacing with a local Error type)

Ok thanks Wez! Would you mind pinging me or something once you've done your changes and made the release? Many thanks :)

**Comment by wez** [comment]
I've published filedescriptor 0.8

**Comment by robinbernon** [comment]
Thanks!

**Pull request closed without merging**
