### PR TITLE
Fix: changing background color for Dark+ theme

### PR DESCRIPTION
**Pull request by saccarosium**
Fixing the background color since every instance of the theme is used.

### CODE REVIEW

**Comment by wez** [comment]
Thanks for digging in!

That file is synchronized from data in https://github.com/mbadolato/iTerm2-Color-Schemes and this edit will be lost when I next re-sync. Can you get a PR in over there first, and then we can sync it back?

https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/schemes/Dark%2B.itermcolors is the source file, then you'd need to run https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/tools/update_all.py and submit the changes as a PR to that repo.

**Comment by saccarosium** [comment]
Ok, I will do that thanks

**Comment by saccarosium** [comment]
I've notice that there is only one version of gruvbox in the repos, also I don't
see some famous colorschemes. I would like to add them. Do you know how to
submit other colorscheme and automatically create colorschemes to the others
terminals?

**Comment by wez** [comment]
Thanks!

**Pull request closed without merging**
