### PR TITLE
docs: "|" needs to compose with mod SHIFT to work

### PR DESCRIPTION
**Pull request by Xuanwo**
Signed-off-by: Xuanwo <github@xuanwo.io>

### CODE REVIEW

**Comment by wez** [comment]
Thanks for diving in!  What OS are you using? I don't believe that SHIFT is necessary here, but the behavior has varied a bit over the past couple of releases

**Comment by Xuanwo** [comment]
I'm using Archlinux:

```shell
:) neofetch
                   -`                    xuanwo
                  .o+`                   ------------------
                 `ooo/                   OS: Arch Linux x86_64
                `+oooo:                  Host: 90RC00EGCP LEGION REN7000P-26AMR
               `+oooooo:                 Kernel: 5.17.1-zen1-1-zen
               -+oooooo+:                Uptime: 7 hours, 17 mins
             `/:-:++oooo+:               Packages: 1052 (pacman)
            `/++++/+++++++:              Shell: zsh 5.8.1
           `/++++++++++++++:             Resolution: 3840x2160
          `/+++ooooooooooooo/`           DE: Plasma 5.24.4
         ./ooosssso++osssssso+`          WM: KWin
        .oossssso-````/ossssss+`         Theme: Breeze Light [Plasma], Breeze [GTK2/3]
       -osssssso.      :ssssssso.        Icons: [Plasma], candy-icons [GTK2/3]
      :osssssss/        osssso+++.       Terminal: WezTerm
     /ossssssss/        +ssssooo/-       CPU: AMD Ryzen 9 5950X (32) @ 3.400GHz
   `/ossssso+/:-        -:/+osssso+-     GPU: AMD ATI Radeon RX 6800/6800 XT / 6900 XT
  `+sso+:-`                 `.-/+oso:    Memory: 11418MiB / 64228MiB
 `++:.                           `-/+/
 .`                                 `/
```

Here is my key binding debug log:

Without shift:

```shell
:) wezterm --config debug_key_events=true
16:31:30.803  INFO   wezterm_mux_server_impl::local > setting up /run/user/1000/wezterm/gui-sock-44970
16:31:30.850  INFO   wezterm_gui::termwindow        > OpenGL initialized! AMD Radeon RX 6900 XT (sienna_cichlid, LLVM 13.0.1, DRM 3.44, 5.17.1-zen1-1-zen) 4.6 (Compatibility Profile) Mesa 22.0.1 is_context_loss_possible=false wezterm version: 20220408-101518-b908e2dd
16:31:30.850  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('\r'), modifiers: NONE, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(Return), modifiers: NONE, phys_code: Some(Return), raw_code: 36, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
16:31:30.850  INFO   wezterm_gui::termwindow::keyevent > send to pane UP key=Enter mods=NONE
16:31:35.155  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(CapsLock), modifiers: CTRL, phys_code: Some(CapsLock), raw_code: 66, repeat_count: 1, key_is_down: true, handled: Handled(false) }
16:31:35.155  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Control, modifiers: CTRL, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(CapsLock), modifiers: CTRL, phys_code: Some(CapsLock), raw_code: 66, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
16:31:35.155  INFO   wezterm_gui::termwindow::keyevent > send to pane DOWN key=Control mods=CTRL
16:31:35.663  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(A), modifiers: CTRL, phys_code: Some(A), raw_code: 38, repeat_count: 1, key_is_down: true, handled: Handled(false) }
16:31:35.663  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('a'), modifiers: CTRL, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(A), modifiers: CTRL, phys_code: Some(A), raw_code: 38, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
16:31:35.795  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('a'), modifiers: CTRL, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(A), modifiers: CTRL, phys_code: Some(A), raw_code: 38, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
16:31:35.795  INFO   wezterm_gui::termwindow::keyevent > send to pane UP key=Char('a') mods=CTRL
16:31:35.863  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Control, modifiers: NONE, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(CapsLock), modifiers: NONE, phys_code: Some(CapsLock), raw_code: 66, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
16:31:35.863  INFO   wezterm_gui::termwindow::keyevent > send to pane UP key=Control mods=NONE
16:31:36.207  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(Backslash), modifiers: NONE, phys_code: Some(Backslash), raw_code: 51, repeat_count: 1, key_is_down: true, handled: Handled(false) }
16:31:36.207  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('\\'), modifiers: NONE, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(Backslash), modifiers: NONE, phys_code: Some(Backslash), raw_code: 51, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
16:31:36.290  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('\\'), modifiers: NONE, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(Backslash), modifiers: NONE, phys_code: Some(Backslash), raw_code: 51, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
16:31:36.290  INFO   wezterm_gui::termwindow::keyevent > send to pane UP key=Char('\\') mods=NONE
```

With shift:

```shell
16:32:18.410  INFO   wezterm_mux_server_impl::local > setting up /run/user/1000/wezterm/gui-sock-45198
16:32:18.454  INFO   wezterm_gui::termwindow        > OpenGL initialized! AMD Radeon RX 6900 XT (sienna_cichlid, LLVM 13.0.1, DRM 3.44, 5.17.1-zen1-1-zen) 4.6 (Compatibility Profile) Mesa 22.0.1 is_context_loss_possible=false wezterm version: 20220408-101518-b908e2dd
16:32:18.474  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('\r'), modifiers: NONE, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(Return), modifiers: NONE, phys_code: Some(Return), raw_code: 36, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
16:32:18.474  INFO   wezterm_gui::termwindow::keyevent > send to pane UP key=Enter mods=NONE
16:32:19.642  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(CapsLock), modifiers: CTRL, phys_code: Some(CapsLock), raw_code: 66, repeat_count: 1, key_is_down: true, handled: Handled(false) }
16:32:19.642  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Control, modifiers: CTRL, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(CapsLock), modifiers: CTRL, phys_code: Some(CapsLock), raw_code: 66, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
16:32:19.642  INFO   wezterm_gui::termwindow::keyevent > send to pane DOWN key=Control mods=CTRL
16:32:19.830  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(A), modifiers: CTRL, phys_code: Some(A), raw_code: 38, repeat_count: 1, key_is_down: true, handled: Handled(false) }
16:32:19.831  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('a'), modifiers: CTRL, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(A), modifiers: CTRL, phys_code: Some(A), raw_code: 38, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
16:32:19.930  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Control, modifiers: NONE, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(CapsLock), modifiers: NONE, phys_code: Some(CapsLock), raw_code: 66, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
16:32:19.930  INFO   wezterm_gui::termwindow::keyevent > send to pane UP key=Control mods=NONE
16:32:19.930  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('a'), modifiers: NONE, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(A), modifiers: NONE, phys_code: Some(A), raw_code: 38, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
16:32:19.930  INFO   wezterm_gui::termwindow::keyevent > send to pane UP key=Char('a') mods=NONE
16:32:20.138  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(LeftShift), modifiers: SHIFT, phys_code: Some(LeftShift), raw_code: 50, repeat_count: 1, key_is_down: true, handled: Handled(false) }
16:32:20.138  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Shift, modifiers: SHIFT, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(LeftShift), modifiers: SHIFT, phys_code: Some(LeftShift), raw_code: 50, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
16:32:20.138  INFO   wezterm_gui::termwindow::keyevent > send to pane DOWN key=Shift mods=SHIFT
16:32:20.258  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(Backslash), modifiers: SHIFT, phys_code: Some(Backslash), raw_code: 51, repeat_count: 1, key_is_down: true, handled: Handled(false) }
16:32:20.258  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('|'), modifiers: SHIFT, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(Backslash), modifiers: SHIFT, phys_code: Some(Backslash), raw_code: 51, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
16:32:20.258  INFO   wezterm_gui::termwindow::keyevent > Char('|') SHIFT | LEADER -> perform SplitHorizontal(SpawnCommand domain=CurrentPaneDomain)
16:32:20.342  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('|'), modifiers: SHIFT, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(Backslash), modifiers: SHIFT, phys_code: Some(Backslash), raw_code: 51, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
16:32:20.342  INFO   wezterm_gui::termwindow::keyevent > send to pane UP key=Char('|') mods=SHIFT
16:32:20.430  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Shift, modifiers: NONE, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(LeftShift), modifiers: NONE, phys_code: Some(LeftShift), raw_code: 50, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
16:32:20.430  INFO   wezterm_gui::termwindow::keyevent > send to pane UP key=Shift mods=NONE
```

**Comment by Xuanwo** [comment]
@wez Hi, is there any help I can provide for this PR?

**Comment by wez** [comment]
Can you try this without the SHIFT with the latest nightly build?

**Comment by Xuanwo** [comment]
Behavior under the current `main` branch:

Without shift:

```shell
:) ./target/debug/wezterm
23:41:36.679  INFO   wezterm_gui::termwindow > OpenGL initialized! AMD Radeon RX 6900 XT (sienna_cichlid, LLVM 13.0.1, DRM 3.44, 5.17.3-zen1-1-zen) 4.6 (Compatibility Profile) Mesa 22.0.1 is_context_loss_possible=false wezterm version: 20220417-083826-e3bc607c
wezterm on  main via 🦀 v1.60.0 took 17s
:) ./target/debug/wezterm --config debug_key_events=true
23:42:20.176  INFO   wezterm_gui::termwindow > OpenGL initialized! AMD Radeon RX 6900 XT (sienna_cichlid, LLVM 13.0.1, DRM 3.44, 5.17.3-zen1-1-zen) 4.6 (Compatibility Profile) Mesa 22.0.1 is_context_loss_possible=false wezterm version: 20220417-083826-e3bc607c
23:42:23.947  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(CapsLock), modifiers: NONE, phys_code: Some(CapsLock), raw_code: 66, repeat_count: 1, key_is_down: true, handled: Handled(false) }
23:42:23.947  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Control, modifiers: NONE, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(CapsLock), modifiers: NONE, phys_code: Some(CapsLock), raw_code: 66, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
23:42:23.947  INFO   wezterm_gui::termwindow::keyevent > send to pane DOWN key=Control mods=NONE
23:42:24.131  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(A), modifiers: CTRL, phys_code: Some(A), raw_code: 38, repeat_count: 1, key_is_down: true, handled: Handled(false) }
23:42:24.132  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('a'), modifiers: CTRL, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(A), modifiers: CTRL, phys_code: Some(A), raw_code: 38, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
23:42:24.199  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Control, modifiers: CTRL, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(CapsLock), modifiers: CTRL, phys_code: Some(CapsLock), raw_code: 66, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
23:42:24.199  INFO   wezterm_gui::termwindow::keyevent > send to pane UP key=Control mods=CTRL
23:42:24.239  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('a'), modifiers: NONE, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(A), modifiers: NONE, phys_code: Some(A), raw_code: 38, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
23:42:24.239  INFO   wezterm_gui::termwindow::keyevent > send to pane UP key=Char('a') mods=NONE
23:42:24.463  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(Backslash), modifiers: NONE, phys_code: Some(Backslash), raw_code: 51, repeat_count: 1, key_is_down: true, handled: Handled(false) }
23:42:24.464  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('\\'), modifiers: NONE, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(Backslash), modifiers: NONE, phys_code: Some(Backslash), raw_code: 51, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
23:42:24.539  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('\\'), modifiers: NONE, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(Backslash), modifiers: NONE, phys_code: Some(Backslash), raw_code: 51, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
23:42:24.539  INFO   wezterm_gui::termwindow::keyevent > send to pane UP key=Char('\\') mods=NONE
```

With Shift

```shell
:( ./target/debug/wezterm --config debug_key_events=true
23:43:17.987  INFO   wezterm_gui::termwindow > OpenGL initialized! AMD Radeon RX 6900 XT (sienna_cichlid, LLVM 13.0.1, DRM 3.44, 5.17.3-zen1-1-zen) 4.6 (Compatibility Profile) Mesa 22.0.1 is_context_loss_possible=false wezterm version: 20220417-083826-e3bc607c
23:43:18.943  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(CapsLock), modifiers: CTRL, phys_code: Some(CapsLock), raw_code: 66, repeat_count: 1, key_is_down: true, handled: Handled(false) }
23:43:18.944  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Control, modifiers: CTRL, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(CapsLock), modifiers: CTRL, phys_code: Some(CapsLock), raw_code: 66, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
23:43:18.944  INFO   wezterm_gui::termwindow::keyevent > send to pane DOWN key=Control mods=CTRL
23:43:19.183  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(A), modifiers: CTRL, phys_code: Some(A), raw_code: 38, repeat_count: 1, key_is_down: true, handled: Handled(false) }
23:43:19.184  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('a'), modifiers: CTRL, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(A), modifiers: CTRL, phys_code: Some(A), raw_code: 38, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
23:43:19.299  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Control, modifiers: NONE, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(CapsLock), modifiers: NONE, phys_code: Some(CapsLock), raw_code: 66, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
23:43:19.299  INFO   wezterm_gui::termwindow::keyevent > send to pane UP key=Control mods=NONE
23:43:19.311  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('a'), modifiers: NONE, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(A), modifiers: NONE, phys_code: Some(A), raw_code: 38, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
23:43:19.311  INFO   wezterm_gui::termwindow::keyevent > send to pane UP key=Char('a') mods=NONE
23:43:19.895  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(LeftShift), modifiers: SHIFT, phys_code: Some(LeftShift), raw_code: 50, repeat_count: 1, key_is_down: true, handled: Handled(false) }
23:43:19.895  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Shift, modifiers: SHIFT, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(LeftShift), modifiers: SHIFT, phys_code: Some(LeftShift), raw_code: 50, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
23:43:19.895  INFO   wezterm_gui::termwindow::keyevent > send to pane DOWN key=Shift mods=SHIFT
23:43:20.011  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(Backslash), modifiers: SHIFT, phys_code: Some(Backslash), raw_code: 51, repeat_count: 1, key_is_down: true, handled: Handled(false) }
23:43:20.012  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('|'), modifiers: SHIFT, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(Backslash), modifiers: SHIFT, phys_code: Some(Backslash), raw_code: 51, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
23:43:20.099  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('|'), modifiers: SHIFT, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(Backslash), modifiers: SHIFT, phys_code: Some(Backslash), raw_code: 51, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
23:43:20.099  INFO   wezterm_gui::termwindow::keyevent > send to pane UP key=Char('|') mods=SHIFT
23:43:20.211  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Shift, modifiers: NONE, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(LeftShift), modifiers: NONE, phys_code: Some(LeftShift), raw_code: 50, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
23:43:20.211  INFO   wezterm_gui::termwindow::keyevent > send to pane UP key=Shift mods=NONE
```

**Comment by wez** [comment]
OK, for now, let's take this.  I would like to fix this, but knowing whether shift or alt contributed to the mapped form of the key, cross platform, is tricky!

Thanks!

**Pull request merged**
