### PR TITLE
wayland: hide mouse cursor when typing

### PR DESCRIPTION
**Pull request by jmbaur**
Fixes wayland not hiding the cursor when typing from issue #618.

### CODE REVIEW

**Comment by wez** [comment]
Looks good, thank you!

**Comment by hgaiser** [comment]
I seem to be getting issues with my cursor hiding and not reappearing. It might be related to neovim (or the way neovim captures mouse events), as it only seems to happen there (but not always).

Steps to reproduce:

1. Open a file in neovim with `set mouse=a`.
1. Click with the mouse inside the neovim window.
1. Press Shift or some other key, the cursor should be hidden.
1. Move the cursor, it doesn't reappear until it leaves the window.

I will test it in X11 to see if the same issue occurs there.

**Comment by sandikata** [comment]
This issue is still there, even with latest commits.

**Comment by wez** [comment]
This is a pull request, not a bug.
If you have an issue, file an issue: https://github.com/wez/wezterm/issues/new?assignees=&labels=bug&template=bug.yml

**Pull request merged**
