### PR TITLE
Change `Exec` command in desktop file to `wezterm start --`

### PR DESCRIPTION
**Pull request by Anomalocaridid**
Some systems rely on the default terminal emulator's desktop entry for things like launching terminal applications with an application launcher or having a resource opener open a file with a terminal application. Currently, setting WezTerm as the default terminal emulator without overriding its desktop file breaks functionality like this because its desktop entry uses `wezterm` instead of `wezterm start` in its `Exec` field, which just terminates with an error when it is passed a command to run.

### CODE REVIEW

**Comment by wez** [comment]
Interesting!  What do you think about also adding in something like `--cwd .` in there?
I'm wondering if that might resolve issues like https://github.com/wez/wezterm/issues/2103, assuming those other applications are resolving how to run wezterm via the .desktop file

**Comment by Anomalocaridid** [comment]
I was able to replicate the problem with Dolphin in #2103 and I appear to have fixed it by setting the `Exec` field in WezTerm's desktop entry to `wezterm start --cwd . --`.

**Comment by wez** [comment]
Thanks!

**Comment by vimpostor** [comment]
FYI I think this commit broke `mailto:` links when using `wezterm` as default terminal emulator with a terminal email client.

For example when `mutt` is configured as the default email program, executing `xdg-open 'mailto:test@test.com'` prints the following error:

```
kf.kio.core: Terminal "wezterm start --cwd . --" not found, service "Mutt"
kf.kio.gui: "Terminal „wezterm start --cwd . --“ beim Versuch, „~/.local/share/applications/mutt.desktop“ auszuführen, nicht gefunden"
```

From a quick glance at the XDG spec it looks like it isn't a wezterm bug though, the `Exec=` line in the desktop file is allowed to be a whole command line, so I guess I should report the bug at KDE instead.

**Pull request merged**
