### PR TITLE
no close-on-exec for stdio file descriptors

### PR DESCRIPTION
**Pull request by mcr**
redirect_stdio_impl incorrectly marks new file descriptor as close-on-exec.
This is because of the dup2/dup3 calls buried down there.  
Changing this to call cloexec() only when needed seems difficult to get right for all paths through, so instead, just unmark the file descriptor as close-on-exec.
Looked for, but did not find, any test cases on this code, would like to add a test case here.

### CODE REVIEW

**Comment by mcr** [comment]
https://github.com/tokio-rs/tokio/issues/4053

**Comment by wez** [comment]
This seems reasonable to me, thanks!
@robinbernon any objection to this?

**Comment by robinbernon** [comment]
> This seems reasonable to me, thanks!
> @robinbernon any objection to this?

Sounds good to me 👍

**Comment by wez** [comment]
OK, this is now published as filedescriptor 0.8.1

**Pull request merged**
