### PR TITLE
Colorschemes: add Tokyo Night theme.

### PR DESCRIPTION
**Pull request by Zawaken**
Adding the Tokyo Night colorscheme with all its variants.

The contents of the .toml files were found [here](https://github.com/folke/tokyonight.nvim/tree/main/extras)

Here are the specific files I've taken it from:
[Tokyo Night: Day](https://github.com/folke/tokyonight.nvim/blob/main/extras/wezterm_tokyonight_day.toml)
[Tokyo Night: Night](https://github.com/folke/tokyonight.nvim/blob/main/extras/wezterm_tokyonight_night.toml)
[Tokyo Night: Storm](https://github.com/folke/tokyonight.nvim/blob/main/extras/wezterm_tokyonight_storm.toml)

I am unsure how the screenshots in docs/colorschemes/* were taken, if I knew how to replicate them, I could have added them as well.

Edit: I saw in the documentation that WezTerm uses iTerm2-Color-Schemes for its Colorschemes, this pull request might be better suited there, let me know if that is the case, and I can open a PR there instead.

### CODE REVIEW

**Comment by wez** [comment]
Thanks!

> Edit: I saw in the documentation that WezTerm uses iTerm2-Color-Schemes for its Colorschemes, this pull request might be better suited there, let me know if that is the case, and I can open a PR there instead.

Yes please!  That way your work to port it can be used in other terminals as well!

The screenshots are generated by a script that I run periodically: don't worry about that in the context of this PR.

**Comment by Zawaken** [comment]
Well, seems like someone might have done it before me in the iTerm-Color-Schemes repo.

[Link to commit](https://github.com/mbadolato/iTerm2-Color-Schemes/commit/2c9be4b318de93f0ea617e46f99096dbcba42da9)

So I guess it already exists in the repository, and all that is needed is a sync or something.

**Comment by wez** [comment]
Looks like there are a few to sync; I'll take care of that out of band and update the screenshots

**Comment by wez** [comment]
Sync'd; it'll take about an hour before the various builds complete and have this available in the nightly downloads.

**Comment by Zawaken** [comment]
Thanks! :smile:

**Pull request closed without merging**
