### PR TITLE
fix: docs typos

### PR DESCRIPTION
**Pull request by mozumasu**
Fixing some typos I encountered in the docs.

### CODE REVIEW

**Comment by loops** [comment]
Hi  mozumasu,

Most of the changes look good, but three of the diffs incorrectly shuffle the lines, while making the edit.

**Comment by mozumasu** [comment]
Thank you for checking!
I have made the corrections!
[0571d09e](https://github.com/wez/wezterm/pull/6073/commits/0571d09e33862ea2503e794e71ae102766d6fc81)

**Comment by loops** [comment]
Looks all-good now!

**Comment by wez** [comment]
Thank you!

**Pull request merged**
