### PR TITLE
No need --cask flags anymore

### PR DESCRIPTION
**Pull request by Goooler**
No need to add it for Brew installation/uninstallation now.

### CODE REVIEW

**Comment by wez** [comment]
are you sure about this? ISTR that there was some ambiguity in the past and that it was in fact necessary to use `--cask` to guarantee that wezterm's authentic CI-produced and signed binaries were installed

**Comment by Goooler** [comment]
I installed wezterm without this option from official cask repo.

**Comment by rawnly** [comment]
According to homebrew docs this is needed

https://formulae.brew.sh/cask/1password
https://formulae.brew.sh/cask/wezterm

**Comment by Goooler** [comment]
This is necessary if there is both a cask and a formula present.

**Comment by wez** [comment]
We're going to keep the flag because I feel like there have been at least two different occasions where we've been bitten by not having it.

**Pull request closed without merging**
